services:
  postgres:
    image: postgres:16
    container_name: autoflex-postgres
    environment:
      POSTGRES_DB: autoflex
      POSTGRES_USER: autoflex
      POSTGRES_PASSWORD: autoflex
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U autoflex -d autoflex"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: autoflex-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      QUARKUS_PROFILE: dev
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/autoflex
      QUARKUS_DATASOURCE_USERNAME: autoflex
      QUARKUS_DATASOURCE_PASSWORD: autoflex
      QUARKUS_HIBERNATE_ORM_SCHEMA_MANAGEMENT_STRATEGY: drop-and-create
      QUARKUS_HIBERNATE_ORM_SQL_LOAD_SCRIPT: import.sql
    ports:
      - "8080:8080"
